name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{1bf67564-2b38-4b5c-800d-adca4514b7dc}}
          heroku_app_name: "Raphaël Christen" #Must be unique in Heroku
          heroku_email: "raphael.christen@edu.ece.fr"